server:
  port: 9002

spring:
  application:
    name: admin-server
  #系统监控
  boot:
    admin:
      url: http://localhost:9002

# 关闭安全管理
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false


