server:
  port: 9004

spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/show_sky/dms_configuration
#          default-label: ${spring.profiles.active} #解决监控down
          search-paths: repo
      label: master
  boot:
    admin:
      url: http://localhost:9002
# 关闭安全管理
management:
  security:
    enabled: false
endpoints:
  health:
    sensitive: false


---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka666@localhost:9003/eureka
    registry-fetch-interval-seconds: 10
---
spring:
  profiles: prd
  cloud:
    config:
      retry:
        initial-interval: 3000
        multiplier: 1.5
        max-interval: 20000
        max-attempts: 6
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:eureka666@eureka:9003/eureka
